import localFont from "next/font/local";
import "./globals.css";
import Navber from "@/components/Navber/Navber";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: { default: "Xmade-Hore", template: "%s | Xmade-Hore" },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navber></Navber>
        <div className="my-4 px-6">{children}</div>
      </body>
    </html>
  );
}
